# Generated by Django 5.0.4 on 2024-04-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0012_formulaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnee',
            name='Adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordonnee',
            name='Nom',
            field=models.TextField(blank=True, null=True),
        ),
    ]
